### ISSUE TITLE
Buttons are wonky - no right edge, no bottom edge, problems with onhover and onclick

### ISSUE THREAD

**Issue by greysondn** [haxeui/haxeui-flixel#20]
Again, one I've written up the text for so I'll just paste it here.

In my repo: [04-buttonsborked](https://github.com/greysondn/haxeui-tests/tree/master/04-buttonsborked)
Specific commit: [41e19b9](https://github.com/greysondn/haxeui-tests/tree/41e19b9fc0814b1202774189cd7b2cf6b9fcb266/04-buttonsborked)
Zipped version attached to this issue: [04-buttonsborked.zip](https://github.com/haxeui/haxeui-flixel/files/3907914/04-buttonsborked.zip)

---

I've noticed that buttons don't have a right edge anymore, and some buttons go
kinda wonky when you hover over them. This project exists to collect those and
any other button-based issues I find in one place.

The top two buttons have no right edge and go completely square if you hover
them.

The bottom two buttons go wonky if you hover them.

There may be others; this however is probably a solid start.

haxelib versions...

`flixel`, `git 4d23ed84`  
`haxeui-core`, `haxelib 1.0.7`  
`haxeui-flixel`, `git 110fd2ac`

Test targets

```
air      - not tested
android  - not tested
electron - not tested
flash    - not tested
html5    - Has this bug.
hashlink - not tested
neko     - not tested
windows  - not tested
```
---

Screenshots:

Right edge missing -
![image](https://user-images.githubusercontent.com/3652901/69910941-d1675180-13e1-11ea-8a31-caad9ba8ecae.png)

Bottom edge missing -
![image](https://user-images.githubusercontent.com/3652901/69910967-40dd4100-13e2-11ea-9d32-90fff2c97e39.png)

Onhover issues -
![image](https://user-images.githubusercontent.com/3652901/69910977-8c8fea80-13e2-11ea-8a9b-4991da36fda6.png)

Onclick issues -
![image](https://user-images.githubusercontent.com/3652901/69910993-c6f98780-13e2-11ea-8427-bdee0266b68a.png)

**Comment by ianharrigan** [comment]
Ive tested this locally and done seem to have the same issues, all looks fine. From your version list it _looks_ like the only difference between us might be flixel itself. 

Can you downgrade to 4.6.1 and if this still happens?

Cheers,
Ian

```
lime: 7.2.1 7.3.0 7.5.0 7.6.1 7.6.2 [7.6.3]
openfl: 6.2.0 8.0.0 8.1.0 8.8.0 8.9.0 8.9.1 8.9.2 8.9.3 8.9.4 8.9.5 [git]
flixel: 4.6.0 [4.6.1]
haxeui-core: 0.0.4 1.0.4 1.0.6 [dev:C:\Work\HaxeUI\haxeui-core]
haxeui-flixel: [dev:C:\Work\HaxeUI\backends\haxeui-flixel]
```

hxcpp (windows):
![image](https://user-images.githubusercontent.com/3024242/69912217-507e7900-1426-11ea-85c3-86b37f17b123.png)

html5:
![image](https://user-images.githubusercontent.com/3024242/69912221-5e33fe80-1426-11ea-8136-d5d826aa047c.png)

**Comment by greysondn** [comment]
Ian:
After setting Flixel to 4.6.1 -
![image](https://user-images.githubusercontent.com/3652901/70021085-65a9f380-155d-11ea-9422-a8e414d169b6.png)

Exhaustive haxelib:
```
dox: 1.1.0 [1.2.0]
flixel-addons: 2.7.1 2.7.3 [2.7.5]
flixel-templates: 2.5.3 2.5.4 2.5.5 2.6.2 [2.6.3]
flixel-tools: 1.4.2 1.4.3 [1.4.4]
flixel-ui: 2.3.1 [2.3.2]
flixel: 4.5.1 4.6.0 [4.6.1] git
formatter: 1.5.1 1.6.0 1.8.1 [1.9.1]
haxeui-core: [1.0.7] git old
haxeui-flixel: 0.0.0 [git]
hscript: [2.3.0]
hxcpp-debug-server: [dev:c:\Users\Dorian Greyson\.vscode\extensions\vshaxe.hxcpp-debugger-1.2.4\hxcpp-debug-server]
hxcpp: 4.0.4 4.0.8 4.0.19 4.0.52 [4.0.64]
lime: 7.2.0 7.2.1 7.3.0 7.5.0 7.6.1 [7.6.3]
openfl-tools: [1.0.10]
openfl: 8.7.0 8.8.0 8.9.1 8.9.3 [8.9.5]
yaml: 1.3.0 [fix-your-lib] git
```

Not a clue. Project config only includes:
```
<haxelib name="flixel" />
<haxelib name="haxeui-core" />
<haxelib name="haxeui-flixel" />
```

---

Edit: I removed about half my haxelibs and did a clean on the project... the libs were unrelated, and the problem persists. But at least that should make that list easier to read now and in the future.

---

Edit2:
Currently poking and prodding. Maybe we're lucky and I'm an idiot. Still in process of testing.
```
C:\WINDOWS\system32>haxelib update
Checking dox
Checking flixel
flixel was updated
Checking flixel-addons
Checking flixel-templates
Checking flixel-tools
Checking flixel-ui
Checking formatter
Checking haxeui-core
haxeui-core was updated
Checking haxeui-flixel
haxeui-flixel was updated
Checking hscript
Checking hxcpp
Checking hxcpp-debug-server
Failed with error: No such Project : hxcpp-debug-server
Checking lime
Checking openfl
Checking openfl-tools
Checking yaml
yaml was updated
Done
```

---

Edit 3: No love there. You're running a git version of openfl; now trying that.

**Comment by greysondn** [comment]
Deliberate double comment. It's OpenFL. That's the missing dependency here.

![image](https://user-images.githubusercontent.com/3652901/70055609-e42b8300-15a7-11ea-92d8-182823e49e9d.png)

Kick it back to 8.9.5 and it breaks. Kick it forwards to git ae6f1401b433 and it works correctly. Later commits will likely work fine; that's their current `develop` branch commit as of this writing.

If there's nothing you need from me, it appears this can be closed. At least on the face of it.

**Comment by ianharrigan** [comment]
OK, great - ill close this then

Cheers,
Ian
