### ISSUE TITLE
Nothing working. (If this project is discontinued pls let me know)

### ISSUE THREAD

**Issue by Arolox666** [haxeui/haxeui-flixel#47]
## Expected Behavior

When pointing on any UI element the game should not try to switch the cursor or at least not crash the game

## Current Behavior

When pointing on ANY UI element the game crashes saying a image with and specific ID was not found

## Possible Solution

IDK I'm not good at coding

## Steps to Reproduce (for bugs)

1. Paste the code provided into and empty PlayState
2. Compile to windows or any other platform
3. Point on the slider
4. Enjoy your newly crashed game

## Media

![image](https://github.com/haxeui/haxeui-flixel/assets/168214112/166eff34-8a4a-4d8d-83d7-48989b2951af)

https://github.com/haxeui/haxeui-flixel/assets/168214112/9fb06f45-259a-499e-b299-3eb5cd58b15e

## Test app / minimal test case

import flixel.FlxState;
import haxe.ui.Toolkit;
import haxe.ui.components.Button;
import haxe.ui.components.VerticalSlider;

class PlayState extends FlxState
{
	override public function create()
	{
		super.create();
		Toolkit.init();

		var slider = new VerticalSlider(); //Slider or literally anything else
		add(slider);
	}

	override public function update(elapsed:Float)
	{
		super.update(elapsed);
	}
}

## Context

I was just trying to make a simple volume control in my Windows Simulator but flixel-ui's slider is broken so my only resort was haxeui but when I actually loaded up and tried to move the slider the game crashed.

## Your Environment

*Haxe Version: latest or 4.1.0
*Haxeui-core version: latest or 1.7.0
*Haxeui-flixel version: latest or 1.7.0
*Flixel version: latest or 5.8.0
*OS Version if it has to do something with it: Windows 11

**Comment by ianharrigan** [comment]
Is that image there in haxeui-flixe? I wonder if updating to latest git version of haxeui-core and haxeui-flixel will fix it?

**Comment by Arolox666** [comment]
OMG! Thank you!!! I had to use git this whole time!? I was using haxelib install haxeui-flixel/core this whole time.
Edit: Everything now works how it's supossed to Thank You very much again dude.
